l2leaf_node_group: RACK2_MLAG
switch_platform: vEOS-LAB
leaf_id: 2
switch_mgmt_ip: 192.168.1.11/24
leaf_filter_tenants:
- all
leaf_filter_tags:
- all
leaf_allowed_vrfs:
- Common_VRF
leaf_allowed_svis:
- 110
- 111
- 112
leaf_allowed_vlans:
- 110
- 111
- 112
leaf_mlag: true
leaf_mlag_group: RACK2_MLAG
leaf_mlag_role: primary
leaf_mlag_peer: DC1-POD1-L2LEAF2B
leaf_mlag_ip: 2
leaf_mlag_peer_ip: 3
leaf_mlag_peer_id: 3
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr: null
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval: null
queue_monitor_length: null
name_server: null
ntp_server: null
redundancy: null
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 8192
  no_spanning_tree_vlan: 4094
aaa_authorization: null
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$eJ5TvI8oru5i9e8G$R1X/SbtGTk9xoEHEBQASc7SC2nHYmi.crVgp2pXuCXwxsXEA81e4E0cXgQ6kX08fIeQzauqhv2kS.RGJFCon5/
clock: null
vlans:
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
  4085:
    tenant: system
    name: L2LEAF_INBAND_MGMT
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
vrfs:
  MGMT:
    ip_routing: false
port_channel_interfaces:
  Port-Channel1:
    description: DC1-POD1-LEAF2A_Po3
    type: switched
    shutdown: false
    vlans: 110-112,4085
    mode: trunk
    service_profile: QOS-PROFILE
    mlag: 1
  Port-Channel3:
    description: MLAG_PEER_DC1-POD1-L2LEAF2B_Po3
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    service_profile: QOS-PROFILE
    trunk_groups:
    - MLAG
ethernet_interfaces:
  Ethernet1:
    peer: DC1-POD1-LEAF2A
    peer_interface: Ethernet3
    peer_type: l3leaf
    description: DC1-POD1-LEAF2A_Ethernet3
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: DC1-POD1-LEAF2B
    peer_interface: Ethernet3
    peer_type: l3leaf
    description: DC1-POD1-LEAF2B_Ethernet3
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet3:
    peer: DC1-POD1-L2LEAF2B
    peer_interface: Ethernet3
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-POD1-L2LEAF2B_Ethernet3
    type: switched
    shutdown: false
    channel_group:
      id: 3
      mode: active
  Ethernet4:
    peer: DC1-POD1-L2LEAF2B
    peer_interface: Ethernet4
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-POD1-L2LEAF2B_Ethernet4
    type: switched
    shutdown: false
    channel_group:
      id: 3
      mode: active
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.1.11/24
    gateway: 192.168.1.254
  Vlan4085:
    description: L2LEAF_INBAND_MGMT
    shutdown: false
    mtu: 1500
    ip_address: 172.21.110.5/24
    gateway: 172.21.110.1
vlan_interfaces:
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 172.19.110.2/31
    no_autostate: true
    mtu: 1500
tcam_profile: null
platform: null
mac_address_table: null
ip_igmp_snooping:
  globally_enabled: true
  vlans: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.254
- destination_address_prefix: 0.0.0.0/0
  gateway: 172.21.110.1
mlag_configuration:
  domain_id: RACK2_MLAG
  local_interface: Vlan4094
  peer_address: 172.19.110.3
  peer_link: Port-Channel3
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
