switch_platform: vEOS-LAB
switch_mgmt_ip: 192.168.1.4/24
switch_bgp_as: 65102
switch_router_id: 172.16.10.2
switch_evpn_role: server
switch_evpn_route_servers:
- DC2-POD1-LEAF1A
- DC2-POD1-SPINE1
- DC2-RS1
- DC2-SUPER-SPINE1
switch_evpn_route_clients: []
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr: null
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval: null
queue_monitor_length: null
logging: null
name_server: null
ntp_server: null
redundancy: null
spanning_tree:
  mode: none
aaa_authorization: null
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$eJ5TvI8oru5i9e8G$R1X/SbtGTk9xoEHEBQASc7SC2nHYmi.crVgp2pXuCXwxsXEA81e4E0cXgQ6kX08fIeQzauqhv2kS.RGJFCon5/
clock: null
vrfs:
  MGMT:
    ip_routing: false
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3
ethernet_interfaces:
  Ethernet1:
    peer: DC1-SUPER-SPINE2
    peer_interface: Ethernet5
    peer_type: super-spine
    description: P2P_LINK_TO_DC1-SUPER-SPINE2_Ethernet5
    mtu: 1500
    service_profile: QOS-PROFILE
    type: routed
    shutdown: false
    ip_address: 172.17.10.9/31
  Ethernet2:
    peer: DC1-POD2-SPINE1
    peer_interface: Ethernet4
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD2-SPINE1_Ethernet4
    mtu: 1500
    service_profile: QOS-PROFILE
    type: routed
    shutdown: false
    ip_address: 172.17.10.11/31
  Ethernet3:
    peer: DC1-POD2-LEAF1A
    peer_interface: Ethernet3
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-POD2-LEAF1A_Ethernet3
    mtu: 1500
    service_profile: QOS-PROFILE
    type: routed
    shutdown: false
    ip_address: 172.17.10.13/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 172.16.10.2/32
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.1.4/24
    gateway: 192.168.1.254
tcam_profile: null
platform: null
mac_address_table: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.254
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 172.16.10.0/24 eq 32
  PL-P2P-UNDERLAY:
    sequence_numbers:
      10:
        action: permit 172.17.10.0/24 le 31
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  RM-EVPN-FILTER-AS65200:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65200
      20:
        type: permit
  RM-EVPN-FILTER-AS65201:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65201
      20:
        type: permit
  RM-EVPN-FILTER-AS65210:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65210
      20:
        type: permit
  RM-EVPN-FILTER-AS65211:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65211
      20:
        type: permit
router_bgp:
  as: 65102
  router_id: 172.16.10.2
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '5'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: true
      maximum_routes: 0
      next_hop_unchanged: true
  neighbors:
    172.17.10.8:
      peer_group: IPv4-UNDERLAY-PEERS
      description: DC1-SUPER-SPINE2
      remote_as: 65100
      bfd: true
    172.17.10.10:
      peer_group: IPv4-UNDERLAY-PEERS
      description: DC1-POD2-SPINE1
      remote_as: 65120
      bfd: true
    172.17.10.12:
      peer_group: IPv4-UNDERLAY-PEERS
      description: DC1-POD2-LEAF1A
      remote_as: 65121
      bfd: true
    172.16.210.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC2-POD1-LEAF1A
      remote_as: 65211
      route_map_out: RM-EVPN-FILTER-AS65211
    172.16.210.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC2-POD1-SPINE1
      remote_as: 65210
      route_map_out: RM-EVPN-FILTER-AS65210
    172.16.20.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC2-RS1
      remote_as: 65201
      route_map_out: RM-EVPN-FILTER-AS65201
    172.16.200.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC2-SUPER-SPINE1
      remote_as: 65200
      route_map_out: RM-EVPN-FILTER-AS65200
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  address_family_rtc:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
        default_route_target:
          only: true
router_ospf: null
router_isis: null
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
