l2leaf_node_group: RACK1_SINGLE
switch_platform: vEOS-LAB
leaf_id: 1
switch_mgmt_ip: 192.168.1.23/24
leaf_filter_tenants:
- all
leaf_filter_tags:
- all
leaf_allowed_vrfs:
- Common_VRF
leaf_allowed_svis:
- 110
- 111
- 112
leaf_allowed_vlans:
- 110
- 111
- 112
leaf_mlag: false
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr: null
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval: null
queue_monitor_length: null
name_server: null
ntp_server: null
redundancy: null
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 8192
aaa_authorization: null
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$eJ5TvI8oru5i9e8G$R1X/SbtGTk9xoEHEBQASc7SC2nHYmi.crVgp2pXuCXwxsXEA81e4E0cXgQ6kX08fIeQzauqhv2kS.RGJFCon5/
clock: null
vlans:
  4092:
    tenant: system
    name: L2LEAF_INBAND_MGMT
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
vrfs:
  MGMT:
    ip_routing: false
port_channel_interfaces:
  Port-Channel1:
    description: DC2-POD1-LEAF1A_Po3
    type: switched
    shutdown: false
    vlans: 110-112,4092
    mode: trunk
    service_profile: QOS-PROFILE
ethernet_interfaces:
  Ethernet1:
    peer: DC2-POD1-LEAF1A
    peer_interface: Ethernet3
    peer_type: l3leaf
    description: DC2-POD1-LEAF1A_Ethernet3
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.1.23/24
    gateway: 192.168.1.254
  Vlan4092:
    description: L2LEAF_INBAND_MGMT
    shutdown: false
    mtu: 1500
    ip_address: 172.21.210.4/24
    gateway: 172.21.210.1
vlan_interfaces: null
tcam_profile: null
platform: null
mac_address_table: null
ip_igmp_snooping:
  globally_enabled: true
  vlans: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.254
- destination_address_prefix: 0.0.0.0/0
  gateway: 172.21.210.1
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
