site_name: Arista AVD collection
site_author: Arista Ansible Team
site_description: Arista Validated Design collection's documentation
docs_dir: ansible_collections/arista/avd/
site_favicon: docs/_media/favicon.ico
theme:
  name: material
  features:
    - navigation.instant
    # - toc.integrate
  highlightjs: true
  hljs_languages:
        - yaml
        - python
        - shell
extra_css:
  # - docs/stylesheets/extra.ivory.css
  - docs/stylesheets/extra.material.css

markdown_extensions:
  - mdx_truly_sane_lists
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      separator: "-"
      # permalink: "#"
      permalink: true
      baselevel: 3

copyright: Copyright &copy; 2019 - 2020 Arista Networks
repo_name: AVD on Github
repo_url: https://github.com/aristanetworks/ansible-avd
use_directory_urls: true
nav:
  - Home: README.md
  - Release Notes:
    - 2.0.x: docs/release-notes/2.0.x.md
    - 1.1.x: docs/release-notes/1.1.x.md
    - 1.0.x: docs/release-notes/1.0.x.md
  - Getting Started: docs/getting-started.md
  - Installation:
    - Requirements: docs/installation/requirements.md
    - Setup environment: docs/installation/setup-environement.md
    - Ansible-galaxy installation: docs/installation/setup-galaxy.md
    - Git installation: docs/installation/setup-git.md
    - Development tips & tricks: docs/installation/development.md
  - How-To:
    - Build your first AVD project: docs/how-to/first-project.md
    - Build your first AVD & CVP project: docs/how-to/first-cvp-avd-project.md
    - Use NAT to access eAPI: docs/how-to/lab-with-nat.md
    - AWX & Tower Integration: docs/how-to/tower-integration.md
    - VScode Container: docs/how-to/vscode-container.md
  - Roles documentation:
    - eos_l3ls_evpn: roles/eos_l3ls_evpn/README.md
    - eos_cli_config_gen: roles/eos_cli_config_gen/README.md
    - cvp_configlet_upload: roles/cvp_configlet_upload/README.md
    - eos_config_deploy_cvp: roles/eos_config_deploy_cvp/README.md
    - eos_config_deploy_eapi: roles/eos_config_deploy_eapi/README.md
    - eos_validate_state: roles/eos_validate_state/README.md
    - eos_snapshot: roles/eos_snapshot/README.md
    - dhcp_provisioner: roles/dhcp_provisioner/README.md
    - build_output_folders: roles/build_output_folders/README.md
    - upgrade_tools: roles/upgrade_tools/README.md
  - Modules documentation:
    - Module Inventory to containers: docs/modules/inventory_to_container.rst.md
    - Module Configlet Build configuration: docs/modules/configlet_build_config.rst.md
    - Cloudvision Module documentation: https://cvp.avd.sh/
  - External resources:
    - Ansible collection user guide: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
    - Ansible User guide: https://docs.ansible.com/ansible/latest/user_guide/index.html
  - About:
    - Contribution Guide: docs/contributing.md
    - Ansible Galaxy page: https://galaxy.ansible.com/arista/cvp
    - Arista AVD Modules: https://github.com/aristanetworks/ansible-avd
    - Arista CVP Modules: https://github.com/aristanetworks/ansible-cvp
    - Arista Installation Script: https://github.com/arista-netdevops-community/avd-install
    - Arista Automation Examples: https://github.com/aristanetworks/netdevops-examples
