---
### Port-Channel Interfaces ###
ethernet_interfaces:
  Ethernet1:
    peer: DC1-SPINE1
    peer_interface: Ethernet1
    peer_type: spine
    description: P2P_LINK_TO_DC1-SPINE1_Ethernet1
    mtu: 1500
    type: routed
    ip_address: 172.31.255.1/31

  Ethernet6:
    logging:
      event:
        link_status: true
    peer: SRV-POD02
    peer_interface: Eth1
    peer_type: server
    description: SRV-POD02_Eth1
    mode: trunk
    vlans: 110-111,210-211
    profile: ALL

  Ethernet2:
    peer: SRV-POD03
    peer_interface: Eth1
    peer_type: server
    description: SRV-POD02_Eth1
    mode: trunk
    vlans: 110-111,210-211
    profile: ALL
    storm_control:
      all:
        level: 10
      broadcast:
        level: 500
        unit: pps
      unknown_unicast:
        level: 1
        unit: percent

  Ethernet10:
    description: TEST
    type: routed
    logging:
      event:
        link_status: true

  Ethernet10.101:
    description: SUB Test
    type: l3dot1q
    logging:
      event:
        link_status: true
    mtu: 1500
    ip_address: 10.1.1.1/31
    vrf: C1
    encapsulation:
      dot1q:
        vlan: 101