policy_maps:
  qos:
    PM_REPLICATION_LD:
      classes:
        CM_REPLICATION_LD:
          set:
            dscp: af11
            traffic_class: 2
            drop_precedence: 1
        CM_REPLICATION_LD_2:
          set:
            dscp: af11
            traffic_class: 2
    PM_REPLICATION_LD2:
      classes:
        CM_REPLICATION_LD:
          set:
            dscp: af11
