### VLANs ###
vlans:
  110:
    tenant: Tenant_A
    name: PR01-DMZ
  3010:
    tenant: Tenant_A
    name: MLAG_iBGP_TENANT_A_PROJECT01
    trunk_groups:
      - LEAF_PEER_L3
  3011:
    name: MLAG_iBGP_TENANT_A_PROJECT02
    state: active
    trunk_groups:
      - MY_TRUNK_GROUP
  3012:
    name: MLAG_iBGP_TENANT_A_PROJECT03
    state: suspend
    trunk_groups:
      - MY_TRUNK_GROUP