switch_platform: vEOS-LAB
switch_mgmt_ip: 192.168.200.102/24
switch_bgp_as: 65000
switch_router_id: 192.168.255.2
switch_evpn_role: none
switch_evpn_route_servers: []
switch_evpn_route_clients: []
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 192.168.200.11
    port: 9910
  ingestauth_key: telarista
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval: null
queue_monitor_length: null
name_server:
  source:
    vrf: MGMT
  nodes:
  - 192.168.200.5
  - 8.8.8.8
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 192.168.200.5
redundancy: null
spanning_tree:
  mode: none
aaa_authorization: null
local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: true
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
clock: null
vrfs:
  MGMT:
    ip_routing: false
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
ethernet_interfaces:
  Ethernet6:
    peer: DC1-BL1A
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-BL1A_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.42/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Ethernet7:
    peer: DC1-BL1B
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-BL1B_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.50/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Ethernet1:
    peer: DC1-LEAF1A
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1A_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.2/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Ethernet2:
    peer: DC1-LEAF2A
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2A_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.10/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Ethernet3:
    peer: DC1-LEAF2B
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2B_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.18/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Ethernet4:
    peer: DC1-SVC3A
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-SVC3A_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.26/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Ethernet5:
    peer: DC1-SVC3B
    peer_interface: Ethernet2
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-SVC3B_Ethernet2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.34/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.2/32
    isis_enable: EVPN_UNDERLAY
    isis_passive: true
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.200.102/24
    gateway: 192.168.200.5
tcam_profile: null
platform: null
mac_address_table: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
prefix_lists: null
route_maps: null
peer_filters: null
router_bgp:
  as: 65000
  router_id: 192.168.255.2
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - maximum-paths 4 ecmp 4
  peer_groups: null
  neighbors: null
  redistribute_routes: null
  address_family_evpn: null
  address_family_ipv4:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: false
  address_family_rtc: null
router_ospf: null
router_isis:
  instance: EVPN_UNDERLAY
  net: 49.0001.0001.0000.0002.00
  router_id: 192.168.255.2
  no_passive_interfaces:
  - Ethernet6
  - Ethernet7
  - Ethernet1
  - Ethernet2
  - Ethernet3
  - Ethernet4
  - Ethernet5
  is_type: level-2
  address_family:
  - ipv4 unicast
  isis_af_defaults:
  - maximum-paths 4
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
