name: mkdoc_check
on:
  pull_request:
    branches:
      - 'devel'
    paths:
      - 'mkdocs.yml'
      - 'ansible_collections/arista/avd/docs/**'
      - 'ansible_collections/arista/avd/roles/**/README.md'
      - '.github/workflows/documentation-check.yml'
jobs:
  offline_validation:
    name: 'Validate mkdoc content'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'start docker-compose stack'
        run: |
          cp development/docker-compose.yml .
          sed -i 's/ansible-avd\///g' docker-compose.yml
          docker-compose -f docker-compose.yml up -d webdoc_avd
          docker-compose -f docker-compose.yml ps

      - name: 'test connectivity to mkdoc server'
        run: |
          until docker exec webdoc_avd curl -s -I http://localhost:8000/ ; do sleep 2; done

      - name: check links for 404
        run: |
          docker run --network container:webdoc_avd raviqqe/muffet:1.5.7 http://127.0.0.1:8000/ -e ".*fonts.gstatic.com.*" -e ".*tools.ietf.org.*" -e ".*edit.*" -f --limit-redirections=3 --timeout=30

      - name: 'stop docker-compose stack'
        run: |
          docker-compose -f docker-compose.yml down
