name: Ansible Molecule for CV Configuration build
on:
  push:
    branches:
      - devel
  pull_request:
    paths:
      - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/tasks/**'
      - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/templates/**'
      - 'ansible_collections/arista/avd/molecules/eos_config_deploy_cvp/**'
      - 'ansible_collections/arista/avd/plugins/**'
      - 'development/requirements**'
      - '.github/workflows/molecule-cvp-deployment.yml'
      # - '.github/git-repo-state-monitor.sh'
jobs:
  molecule:
    name: Run CI test for eos_config_deploy_cvp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'eos_config_deploy_cvp'
          - 'eos_config_deploy_cvp_list'
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
      - uses: actions/checkout@v1

      - name: Run molecule action
        uses: arista-netdevops-community/action-molecule-avd@v1.0
        with:
          molecule_parentdir: 'ansible_collections/arista/avd'
          molecule_command: 'converge'
          molecule_args: '--scenario-name ${{ matrix.avd_scenario }}'
          pip_file: development/requirements.txt
          check_git: true
          check_git_enforced: true
