name: Molecule validation for Release management
on:
  pull_request:
    branches:
      - 'releases/**'
jobs:
  avd_eos_molecule:
    name: Run CI test for AVD EOS Configuration roles
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'evpn_underlay_ebgp_overlay_ebgp'
          - 'evpn_underlay_ospf_overlay_ebgp'
          - 'evpn_underlay_isis_overlay_ibgp'
          - 'eos_l3ls_evpn-twodc-5stage-clos'
          - 'eos_cli_config_gen'
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Run molecule action
        uses: arista-netdevops-community/action-molecule-avd@v1.0
        with:
          molecule_parentdir: 'ansible_collections/arista/avd'
          molecule_command: 'test'
          molecule_args: '--scenario-name ${{ matrix.avd_scenario }}'
          pip_file: development/requirements.txt
          check_git: true
          check_git_enforced: true

  # build_collection:
  #   name: Create Ansible Galaxy collection package
  #   runs-on: ubuntu-18.04
  #   container:
  #     image: avdteam/base:3.6-v2.0
  #     options: --user avd
  #   needs: avd_eos_molecule
  #   steps:

  #   - name: 'set environment variables'
  #     run: |
  #       echo "PY_COLORS=1" >> $GITHUB_ENV
  #       echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV

  #   - uses: actions/checkout@v1

  #   - name: Create package
  #     run: |
  #       make collection-build

  #   - uses: actions/upload-artifact@v2
  #     with:
  #       path: arista-avd.*.tar.gz
