name: Ansible Molecule CLI CONFIG GEN
on:
  pull_request:
    paths:
      - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/tasks/**'
      - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/**'
      - 'ansible_collections/arista/avd/roles/eos_l3ls_evpn/tasks/**'
      - 'ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/**'
      - 'ansible_collections/arista/avd/plugins/**'
      - 'ansible_collections/arista/avd/molecule/**'
      - 'development/requirements**'
      - '.github/workflows/molecule-cli-config-gen.yml'
jobs:
  molecule:
    name: Run CI test for eos_cli_config_gen
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'eos_cli_config_gen'
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Run molecule action
        uses: arista-netdevops-community/action-molecule-avd@v1.0
        with:
          molecule_parentdir: 'ansible_collections/arista/avd'
          molecule_command: 'converge'
          molecule_args: '--scenario-name ${{ matrix.avd_scenario }}'
          pip_file: development/requirements.txt
          check_git: true
          check_git_enforced: true
