name: "PR Notification"
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, locked]
jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - name: 'get environment variables'
        run: |
          echo $GITHUB_REF
