---
scenario:
  converge_sequence:
    - syntax
    - create
    - converge
    - verify
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: DC1-POD1-LEAF1A
    image: avdteam/base:3.6
    pre_build_image: true
    managed: false
    groups:
      - DC1_POD1_LEAFS
      - DC1
      - TWODC_5STAGE_CLOS
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
  inventory:
    links:
      hosts: 'inventory/inventory.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --inventory=inventory/hosts
verifier:
  name: ansible
  inventory:
    links:
      hosts: 'inventory/inventory.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --inventory=inventory/inventory.yml
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
